[package]
name = "proto"
version.workspace = true
edition.workspace = true

[dependencies]
tonic.workspace = true
prost.workspace = true
serde.workspace = true

[build-dependencies]
tonic-build.workspace = true
prost-build.workspace = true
